import fs from 'fs';
import path from 'path';

function escapePdfString(str) {
  return str.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

const pagesData = [
  // Page 1
  [
    "NCERT Physics Class XII Textbook",
    "Chapter Six: ELECTROMAGNETIC INDUCTION",
    "",
    "6.1 INTRODUCTION",
    "",
    "Electricity and magnetism were considered separate and unrelated",
    "phenomena for a long time. In the early decades of the nineteenth century,",
    "experiments on electric current by Oersted, Ampere and a few others",
    "established the fact that electricity and magnetism are inter-related. They",
    "found that moving electric charges produce magnetic fields. For example,",
    "an electric current deflects a magnetic compass needle placed in its vicinity.",
    "This naturally raises the questions like: Is the converse effect possible?",
    "Can moving magnets produce electric currents? Does the nature permit",
    "such a relation between electricity and magnetism? The answer is",
    "resounding yes! The experiments of Michael Faraday in England and",
    "Joseph Henry in USA, conducted around 1830, demonstrated",
    "conclusively that electric currents were induced in closed coils when",
    "subjected to changing magnetic fields. In this chapter, we will study the",
    "phenomena associated with changing magnetic fields and understand",
    "the underlying principles. The phenomenon in which electric current is",
    "generated by varying magnetic fields is appropriately called",
    "electromagnetic induction.",
    "",
    "When Faraday first made public his discovery that relative motion",
    "between a bar magnet and a wire loop produced a small current in the",
    "latter, he was asked, \"What is the use of it?\" His reply was: \"What is the",
    "use of a new born baby?\" The phenomenon of electromagnetic induction",
    "is not merely of theoretical or academic interest but also of practical utility.",
    "Imagine a world where there is no electricity - no electric lights, no trains,",
    "no telephones and no personal computers. Today's civilisation owes its",
    "progress to a great extent to the discovery of electromagnetic induction."
  ],
  // Page 2
  [
    "6.2 THE EXPERIMENTS OF FARADAY AND HENRY",
    "",
    "The discovery and understanding of electromagnetic induction are based on a long",
    "series of experiments carried out by Faraday and Henry. We shall now describe",
    "some of these experiments.",
    "",
    "Experiment 6.1",
    "Figure 6.1 shows a coil C1 connected to a galvanometer G. When the North-pole",
    "of a bar magnet is pushed towards the coil, the pointer in the galvanometer",
    "deflects, indicating the presence of electric current in the coil. The deflection",
    "lasts as long as the bar magnet is in motion. The galvanometer does not show",
    "any deflection when the magnet is held stationary. When the magnet is pulled",
    "away from the coil, the galvanometer shows deflection in the opposite direction,",
    "which indicates reversal of the current's direction.",
    "",
    "Moreover, when the South-pole of the bar magnet is moved towards or away from",
    "the coil, the deflections in the galvanometer are opposite to that observed with",
    "the North-pole for similar movements. Further, the deflection (and hence",
    "current) is found to be larger when the magnet is pushed towards or pulled away",
    "from the coil faster. Instead, when the bar magnet is held fixed and the coil C1",
    "is moved towards or away from the magnet, the same effects are observed.",
    "It shows that it is the relative motion between the magnet and the coil that is",
    "responsible for generation (induction) of electric current in the coil.",
    "",
    "Experiment 6.2",
    "In Fig. 6.2 the bar magnet is replaced by a second coil C2 connected to a battery.",
    "The steady current in the coil C2 produces a steady magnetic field. As coil C2 is",
    "moved towards the coil C1, the galvanometer shows a deflection. This indicates",
    "that electric current is induced in coil C1. When C2 is moved away, the",
    "galvanometer shows a deflection again, but this time in the opposite direction.",
    "The deflection lasts as long as C2 is in motion."
  ],
  // Page 3
  [
    "Experiment 6.3",
    "",
    "The above two experiments involved relative motion between a magnet and a",
    "coil and between two coils, respectively. Through another experiment, Faraday",
    "showed that this relative motion is not an absolute requirement. Figure 6.3 shows",
    "two coils C1 and C2 held stationary. Coil C1 is connected to galvanometer G",
    "while the second coil C2 is connected to a battery through a tapping key K.",
    "",
    "It is observed that the galvanometer shows a momentary deflection when the",
    "tapping key K is pressed. The pointer in the galvanometer returns to zero",
    "immediately. If the key is held pressed continuously, there is no deflection in",
    "the galvanometer. When the key is released, a momentary deflection is observed",
    "again, but in the opposite direction. It is also observed that the deflection",
    "increases dramatically when an iron rod is inserted into the coils along their",
    "axis.",
    "",
    "6.3 MAGNETIC FLUX",
    "",
    "Faraday's great insight lay in discovering a simple mathematical relation to",
    "explain the series of experiments he carried out on electromagnetic induction.",
    "However, before we state and appreciate his laws, we must get familiar with the",
    "notion of magnetic flux, \\( \\Phi_B \\). Magnetic flux is defined in the same way",
    "as electric flux is defined in Chapter 1. Magnetic flux through a plane of area A",
    "placed in a uniform magnetic field B can be written as:",
    "",
    "\\( \\Phi_B = B \\cdot A = BA \\cos \\theta \\)   (Equation 6.1)",
    "",
    "where \\( \\theta \\) is the angle between B and A. The notion of the area as a vector",
    "has been discussed in preceding chapters. If the magnetic field has different",
    "magnitudes and directions at various parts of a surface, then the magnetic flux",
    "is given by the sum over all area elements: \\( \\Phi_B = \\sum B_i \\cdot \\Delta A_i \\).",
    "The SI unit of magnetic flux is Weber (Wb) or Tesla meter squared (T m^2).",
    "Magnetic flux is a scalar quantity."
  ],
  // Page 4
  [
    "6.4 FARADAY'S LAW OF INDUCTION",
    "",
    "From the experimental observations, Faraday arrived at a conclusion that an emf",
    "is induced in a coil when magnetic flux through the coil changes with time.",
    "Experimental observations discussed in Section 6.2 can be explained using this concept.",
    "",
    "The motion of a magnet towards or away from coil C1 in Experiment 6.1 and moving",
    "a current-carrying coil C2 towards or away from coil C1 in Experiment 6.2,",
    "change the magnetic flux associated with coil C1. The change in magnetic flux",
    "induces emf in coil C1. It was this induced emf which caused electric current to",
    "flow in coil C1 and through the galvanometer.",
    "",
    "A plausible explanation for the observations of Experiment 6.3 is as follows:",
    "When the tapping key K is pressed, the current in coil C2 (and the resulting",
    "magnetic field) rises from zero to a maximum value in a short time.",
    "Consequently, the magnetic flux through the neighbouring coil C1 also increases.",
    "It is the change in magnetic flux through coil C1 that produces an induced emf",
    "in coil C1. When the key is held pressed, current in coil C2 is constant.",
    "Therefore, there is no change in the magnetic flux through coil C1 and the",
    "current in coil C1 drops to zero.",
    "",
    "When the key is released, the current in C2 and the resulting magnetic field",
    "decreases from the maximum value to zero in a short time. This results in a",
    "decrease in magnetic flux through coil C1 and hence again induces an electric",
    "current in coil C1. The common point in all these observations is that the time",
    "rate of change of magnetic flux through a circuit induces emf in it.",
    "",
    "Faraday stated experimental observations in the form of a law called",
    "Faraday's law of electromagnetic induction. The law is stated on the next page."
  ],
  // Page 5
  [
    "FARADAY'S LAW OF ELECTROMAGNETIC INDUCTION (Continued)",
    "",
    "The magnitude of the induced emf in a circuit is equal to the time rate of",
    "change of magnetic flux through the circuit.",
    "",
    "Mathematically, the induced emf is given by:",
    "",
    "\\( \\epsilon = - \\frac{d\\Phi_B}{dt} \\)   (Equation 6.3)",
    "",
    "The negative sign indicates the direction of \\( \\epsilon \\) and hence the direction of",
    "current in a closed loop. This will be discussed in detail in the next section.",
    "",
    "In the case of a closely wound coil of N turns, change of flux associated with",
    "each turn is the same. Therefore, the expression for the total induced emf is",
    "given by:",
    "",
    "\\( \\epsilon = - N \\frac{d\\Phi_B}{dt} \\)   (Equation 6.4)",
    "",
    "The induced emf can be increased by increasing the number of turns N of a closed",
    "coil. From equations, we see that the flux can be varied by changing any one",
    "or more of the terms B, A and \\( \\theta \\).",
    "",
    "Example 6.1: Consider Experiment 6.2. (a) What would you do to obtain a large",
    "deflection of the galvanometer? (b) How would you demonstrate the presence",
    "of an induced current in the absence of a galvanometer?",
    "",
    "Solution:",
    "(a) To obtain a large deflection, one or more of the following steps can be taken:",
    "  (i) Use a rod made of soft iron inside the coil C2,",
    "  (ii) Connect the coil to a powerful battery, and",
    "  (iii) Move the arrangement rapidly towards the test coil C1.",
    "(b) Replace the galvanometer by a small bulb, the kind one finds in a small",
    "torch light. The relative motion between the two coils will cause the bulb to",
    "glow and thus demonstrate the presence of an induced current."
  ],
  // Page 6
  [
    "Example 6.2: A square loop of side 10 cm and resistance 0.5 \\( \\Omega \\) is placed",
    "vertically in the east-west plane. A uniform magnetic field of 0.10 T is set up",
    "across the plane in the north-east direction. The magnetic field is decreased",
    "to zero in 0.70 s at a steady rate. Determine the magnitudes of induced emf",
    "and current during this time-interval.",
    "",
    "Solution:",
    "The angle \\( \\theta \\) made by the area vector of the coil with the magnetic field is 45 degrees.",
    "The initial magnetic flux is \\( \\Phi = BA \\cos \\theta = 0.10 \\times (0.1 \\times 0.1) \\times \\cos(45^\\circ) \\)",
    "\\( \\Phi_i = \\frac{10^{-3}}{\\sqrt{2}} \\text{ Wb} \\)",
    "Final flux, \\( \\Phi_f = 0 \\).",
    "The change in flux is brought about in 0.70 s.",
    "The magnitude of the induced emf is given by:",
    "\\( \\epsilon = \\frac{|\\Delta\\Phi_B|}{\\Delta t} = \\frac{10^{-3}}{\\sqrt{2} \\times 0.7} = 1.0 \\text{ mV} \\)",
    "And the magnitude of the current is:",
    "\\( I = \\frac{\\epsilon}{R} = \\frac{1.0 \\times 10^{-3} \\text{ V}}{0.5 \\ \\Omega} = 2 \\text{ mA} \\)",
    "",
    "Example 6.3: A circular coil of radius 10 cm, 500 turns and resistance 2 \\( \\Omega \\) is",
    "placed with its plane perpendicular to the horizontal component of the earth's",
    "magnetic field. It is rotated about its vertical diameter through 180 degrees in",
    "0.25 s. Estimate the magnitudes of the emf and current induced in the coil.",
    "Horizontal component of the earth's magnetic field at the place is 3.0 x 10^-5 T.",
    "",
    "Solution:",
    "Initial flux through the coil \\( \\Phi_{i} = BA \\cos(0^\\circ) = 3.0 \\times 10^{-5} \\times (\\pi \\times 10^{-2}) \\times 1 = 3 \\pi \\times 10^{-7} \\text{ Wb} \\).",
    "Final flux after rotation \\( \\Phi_{f} = 3.0 \\times 10^{-5} \\times (\\pi \\times 10^{-2}) \\times \\cos(180^\\circ) = -3 \\pi \\times 10^{-7} \\text{ Wb} \\).",
    "Estimated value of the induced emf is:",
    "\\( \\epsilon = N \\frac{|\\Delta\\Phi|}{\\Delta t} = 500 \\times \\frac{6\\pi \\times 10^{-7}}{0.25} = 3.8 \\text{ mV} \\)",
    "\\( I = \\frac{\\epsilon}{R} = 1.9 \\text{ mA} \\)."
  ],
  // Page 7
  [
    "6.5 LENZ'S LAW AND CONSERVATION OF ENERGY",
    "",
    "In 1834, German physicist Heinrich Friedrich Lenz (1804-1865) deduced a rule,",
    "known as Lenz's law which gives the polarity of the induced emf in a clear",
    "and concise fashion. The statement of the law is:",
    "",
    "\"The polarity of induced emf is such that it tends to produce a current",
    "which opposes the change in magnetic flux that produced it.\"",
    "",
    "The negative sign shown in Eq. (6.3) represents this effect. We can understand",
    "Lenz's law by examining Experiment 6.1 in Section 6.2.1.",
    "",
    "In Fig. 6.1, we see that the North-pole of a bar magnet is being pushed towards the",
    "closed coil. As the North-pole of the bar magnet moves towards the coil, the",
    "magnetic flux through the coil increases. Hence current is induced in the coil",
    "in such a direction that it opposes the increase in flux. This is possible only",
    "if the current in the coil is in a counter-clockwise direction with respect to",
    "an observer situated on the side of the magnet. Note that magnetic moment",
    "associated with this current has North polarity towards the North-pole of the",
    "approaching magnet.",
    "",
    "Similarly, if the North-pole of the magnet is being withdrawn from the coil,",
    "the magnetic flux through the coil will decrease. To counter this decrease",
    "in magnetic flux, the induced current in the coil flows in clockwise direction",
    "and its South-pole faces the receding North-pole of the bar magnet.",
    "This would result in an attractive force which opposes the motion of the magnet",
    "and the corresponding decrease in flux.",
    "",
    "Lenz's law is in perfect agreement with the Law of Conservation of Energy.",
    "If the induced current flowed in the opposite direction (aiding the change),",
    "the magnet would be attracted with increasing acceleration, creating energy",
    "without work. Thus, mechanical work done in moving the magnet is converted into",
    "electrical energy, which is dissipated by Joule heating."
  ],
  // Page 8
  [
    "Example 6.4: Figure 6.7 shows planar loops of different shapes moving out",
    "of or into a region of a magnetic field which is directed normal to the plane",
    "of the loop away from the reader. Determine the direction of induced current",
    "in each loop using Lenz's law.",
    "",
    "Solution:",
    "(i) The magnetic flux through the rectangular loop abcd increases, due to",
    "the motion of the loop into the region of magnetic field. The induced",
    "current must flow along the path bcdab so that it opposes the increasing flux.",
    "(ii) Due to the outward motion, magnetic flux through the triangular loop abc",
    "decreases due to which the induced current flows along bacb, so as to oppose",
    "the change in flux.",
    "(iii) As the magnetic flux decreases due to motion of the irregular shaped loop",
    "abcd out of the region of magnetic field, the induced current flows along cdabc,",
    "so as to oppose change in flux.",
    "",
    "Example 6.5: (a) A closed loop is held stationary in the magnetic field",
    "between the north and south poles of two permanent magnets held fixed. Can we",
    "hope to generate current in the loop by using very strong magnets?",
    "(b) A closed loop moves normal to the constant electric field between the",
    "plates of a large capacitor. Is a current induced in the loop (i) when it is",
    "wholly inside the region between the capacitor plates (ii) when it is partially",
    "outside the plates of the capacitor? The electric field is normal to the",
    "plane of the loop.",
    "",
    "Solution:",
    "(a) No. However strong the magnet may be, current can be induced only by",
    "changing the magnetic flux through the loop.",
    "(b) No current is induced in either case. Current cannot be induced by",
    "changing the electric flux."
  ],
  // Page 9
  [
    "6.6 MOTIONAL ELECTROMOTIVE FORCE",
    "",
    "Let us consider a straight conductor moving in a uniform and time-independent",
    "magnetic field. Figure 6.10 shows a rectangular conductor PQRS in which the",
    "conductor PQ is free to move. The rod PQ is moved towards the left with a",
    "constant velocity v as shown in the figure.",
    "",
    "Assume that there is no loss of energy due to friction. PQRS forms a closed",
    "circuit enclosing an area that changes as PQ moves. It is placed in a uniform",
    "magnetic field B which is perpendicular to the plane of this system. If the",
    "length RQ = x and RS = l, the magnetic flux \\( \\Phi_B \\) enclosed by the loop PQRS",
    "will be:",
    "",
    "\\( \\Phi_B = Blx \\)",
    "",
    "Since x is changing with time, the rate of change of flux \\( \\Phi_B \\) will induce",
    "an emf given by:",
    "",
    "\\( \\epsilon = -\\frac{d\\Phi_B}{dt} = -\\frac{d}{dt}(Blx) = -Bl\\frac{dx}{dt} \\)",
    "",
    "Since the rod is moving leftward (decreasing x), we use dx/dt = -v, which is",
    "the speed of the conductor PQ. Thus, the induced emf is given by:",
    "",
    "\\( \\epsilon = Blv \\)   (Equation 6.5)",
    "",
    "The induced emf \\( Blv \\) is called motional emf. Thus, we are able to produce",
    "induced emf by moving a conductor instead of varying the magnetic field,",
    "that is, by changing the magnetic flux enclosed by the circuit.",
    "",
    "It is also possible to explain the motional emf expression by invoking the Lorentz",
    "force acting on the free charge carriers of conductor PQ. Consider any charge q",
    "in PQ. The Lorentz force on this charge is qvB in magnitude, and its direction is",
    "towards Q. The work done in moving the charge from P to Q is W = qvBl.",
    "Since emf is the work done per unit charge, \\( \\epsilon = W / q = Blv \\)."
  ],
  // Page 10
  [
    "MOTIONAL ELECTROMOTIVE FORCE (Continued)",
    "",
    "This equation gives emf induced across the rod PQ. On the other hand, it is not",
    "obvious how an emf is induced when a conductor is stationary and the magnetic",
    "field is changing - a fact which Faraday verified by numerous experiments.",
    "In the case of a stationary conductor, the force on its charges is given by:",
    "",
    "\\( F = q (E + v \\times B) = qE \\)   (Equation 6.6)",
    "",
    "since v = 0. Thus, any force on the charge must arise from the electric field",
    "term E alone. Therefore, to explain the existence of induced emf or induced",
    "current, we must assume that a time-varying magnetic field generates an",
    "electric field.",
    "",
    "Example 6.6: A metallic rod of 1 m length is rotated with a frequency of",
    "50 rev/s, with one end hinged at the centre and the other end at the",
    "circumference of a circular metallic ring of radius 1 m, about an axis passing",
    "through the centre and perpendicular to the plane of the ring. A constant",
    "and uniform magnetic field of 1 T parallel to the axis is present everywhere.",
    "What is the emf between the centre and the metallic ring?",
    "",
    "Solution (Method I):",
    "As the rod is rotated, free electrons in the rod move towards the outer end due to",
    "Lorentz force and get distributed over the ring. The resulting separation of charges",
    "produces an emf. The magnitude of the emf generated across a length dr of the",
    "rod is \\( d\\epsilon = B v \\, dr \\). Hence,",
    "\\( \\epsilon = \\int_{0}^{R} B v \\, dr = \\int_{0}^{R} B \\omega r \\, dr = \\frac{B \\omega R^2}{2} \\)",
    "Substituting are values (\\( R = 1 \\text{ m}, \\omega = 2\\pi \\nu = 2\\pi \\times 50 = 100\\pi \\text{ rad/s}, B = 1 \\text{ T} \\)):",
    "\\( \\epsilon = \\frac{1}{2} \\times 1.0 \\times 100\\pi \\times 1^2 = 50\\pi \\approx 157 \\text{ V} \\)."
  ],
  // Page 11
  [
    "Example 6.6 (Continued)",
    "",
    "Solution (Method II):",
    "To calculate the emf, we can imagine a closed loop OPQ in which point O and P area",
    "connected with a resistor R and OQ is the rotating rod.",
    "The potential difference across the resistor is then equal to the induced emf",
    "and equals B x (rate of change of area of loop).",
    "If \\( \\theta \\) is the angle between the rod and the radius of the circle at P",
    "at time t, the area of the sector OPQ is given by:",
    "",
    "\\( A = \\pi R^2 \\times \\frac{\\theta}{2\\pi} = \\frac{1}{2} r^2 \\theta \\)",
    "",
    "where R is the radius of the circle. Hence, the induced emf is:",
    "",
    "\\( \\epsilon = B \\frac{dA}{dt} = B \\frac{d}{dt}\\left(\\frac{1}{2} R^2 \\theta\\right) = \\frac{1}{2} B R^2 \\frac{d\\theta}{dt} = \\frac{1}{2} B R^2 \\omega \\)",
    "",
    "Since \\( \\frac{d\\theta}{dt} = \\omega \\), this expression is identical to the",
    "expression obtained by Method I and we get the same value of 157 V.",
    "",
    "Example 6.7: A wheel with 10 metallic spokes each 0.5 m long is rotated with",
    "a speed of 120 rev/min in a plane normal to the horizontal component of earth's",
    "magnetic field \\( H_E \\) at a place. If \\( H_E = 0.4 \\text{ G} \\) at the place, what",
    "is the induced emf between the axle and the rim of the wheel? Note that",
    "\\( 1 \\text{ G} = 10^{-4} \\text{ T} \\).",
    "",
    "Solution:",
    "Induced emf = \\( \\frac{1}{2} \\omega B R^2 \\)",
    "Given, \\( R = 0.5 \\text{ m} \\), \\( \\nu = 120 \\text{ rev/min} = 2 \\text{ rev/s} \\).",
    "Hence, \\( \\omega = 2\\pi \\nu = 4\\pi \\text{ rad/s} \\).",
    "\\( B = 0.4 \\times 10^{-4} \\text{ T} \\).",
    "Induced emf \\( e = \\frac{1}{2} \\times 4\\pi \\times 0.4 \\times 10^{-4} \\times 0.25 \\approx 6.28 \\times 10^{-5} \\text{ V} \\).",
    "The number of spokes is immaterial because they are in parallel."
  ],
  // Page 12
  [
    "6.7 INDUCTANCE",
    "",
    "An electric current can be induced in a coil by flux change produced by another",
    "coil in its vicinity or flux change produced by the same coil. These two",
    "situations are described separately in the next two sub-sections. However, in",
    "both cases, the flux through a coil is proportional to the current. That is,",
    "\\( \\Phi_B \\propto I \\).",
    "",
    "Further, if the geometry of the coil does not vary with time then,",
    "\\( \\frac{d\\Phi_B}{dt} \\propto \\frac{dI}{dt} \\)",
    "",
    "For a closely wound coil of N turns, the same magnetic flux is linked with all the",
    "turns. When the flux through the coil changes, each turn contributes to the",
    "induced emf. Therefore, a term called flux linkage is used which is equal to",
    "\\( N\\Phi_B \\) for a closely wound coil and in such a case:",
    "",
    "\\( N\\Phi_B \\propto I \\)",
    "\\( N\\Phi_B = L I \\)  or  \\( N\\Phi_B = M I \\)",
    "",
    "The constant of proportionality is called inductance. Its SI unit is henry (H).",
    "",
    "6.7.1 Mutual inductance",
    "Consider Fig. 6.12 which shows two long co-axial solenoids each of length l.",
    "We denote the radius of the inner solenoid S1 by r1 and the number of turns",
    "per unit length by n1. The corresponding quantities for the outer solenoid S2",
    "are r2 and n2, respectively. Let N1 and N2 be the total number of turns",
    "of coils S1 and S2, respectively.",
    "",
    "When a current \\( I_2 \\) is set up through S2, it in turn sets up a magnetic flux",
    "through S1. Let us denote it by \\( \\Phi_1 \\). The corresponding flux linkage",
    "with solenoid S1 is:",
    "\\( N_1\\Phi_1 = M_{12} I_2 \\)   (Equation 6.7)",
    "\\( M_{12} \\) is called the mutual inductance of solenoid S1 with respect to S2.",
    "The magnetic field due to the current \\( I_2 \\) in S2 is \\( B_2 = \\mu_0 n_2 I_2 \\)."
  ],
  // Page 13
  [
    "Mutual inductance (Continued)",
    "",
    "The resulting flux linkage with coil S1 is:",
    "\\( N_1\\Phi_1 = (n_1 l)(\\pi r_1^2)(\\mu_0 n_2 I_2) = \\mu_0 n_1 n_2 \\pi r_1^2 l I_2 \\)   (Equation 6.8)",
    "where \\( n_1 l \\) is the total number of turns \\( N_1 \\) in solenoid S1.",
    "Thus, from the equations, we get:",
    "\\( M_{12} = \\mu_0 n_1 n_2 \\pi r_1^2 l \\)   (Equation 6.9)",
    "",
    "Note that we neglected the edge effects and considered the magnetic field to be",
    "uniform throughout the length and width of the solenoid S2. This is a good",
    "approximation keeping in mind that the solenoid is long.",
    "",
    "We now consider the reverse case. A current \\( I_1 \\) is passed through S1",
    "and the flux linkage with coil S2 is:",
    "\\( N_2\\Phi_2 = M_{21} I_1 \\)   (Equation 6.10)",
    "By symmetry, the calculation gives:",
    "\\( M_{21} = \\mu_0 n_1 n_2 \\pi r_1^2 l \\)   (Equation 6.11)",
    "Comparing, we get:",
    "\\( M_{12} = M_{21} = M \\)   (Equation 6.12)",
    "",
    "We have demonstrated this equality for long co-axial solenoids. However, the",
    "relation is far more general.",
    "",
    "Example 6.8: Two concentric circular coils, one of small radius r1 and the",
    "other of large radius r2, such that \\( r_1 \\ll r_2 \\), are placed co-axially",
    "with centres coinciding. Obtain the mutual inductance of the arrangement.",
    "",
    "Solution:",
    "Let a current \\( I_2 \\) flow through the outer circular coil.",
    "The field at the centre of the coil is \\( B_2 = \\mu_0 I_2 / 2r_2 \\).",
    "Since the inner coil has very small radius, \\( B_2 \\) can be considered uniform.",
    "Hence, \\( \\Phi_1 = \\pi r_1^2 B_2 = \\frac{\\mu_0 \\pi r_1^2}{2r_2} I_2 = M_{12} I_2 \\).",
    "Thus, \\( M = \\frac{\\mu_0 \\pi r_1^2}{2r_2} \\)."
  ],
  // Page 14
  [
    "MUTUAL INDUCTANCE (Continued)",
    "",
    "If a medium of relative permeability \\( \\mu_r \\) had been present, the mutual",
    "inductance would be:",
    "\\( M = \\mu_r \\mu_0 n_1 n_2 \\pi r_1^2 l \\)",
    "",
    "For currents varying with time, equations can be written as:",
    "\\( \\frac{d(N_1\\Phi_1)}{dt} = M \\frac{dI_2}{dt} \\)",
    "Since induced emf in coil C1 is given by \\( \\epsilon_1 = -\\frac{d(N_1\\Phi_1)}{dt} \\),",
    "we get:",
    "\\( \\epsilon_1 = -M \\frac{dI_2}{dt} \\)",
    "This shows that varying current in one coil can induce emf in a neighbouring",
    "coil.",
    "",
    "6.7.2 Self-inductance",
    "In the previous sub-section, we considered the flux in one solenoid due to current",
    "in the other. It is also possible that emf is induced in a single isolated coil",
    "due to change of flux through the coil by means of varying the current through the",
    "same coil. This phenomenon is called self-induction.",
    "",
    "In this case, flux linkage through a coil of N turns is proportional to the",
    "current through the coil and is expressed as:",
    "\\( N\\Phi_B \\propto I \\)",
    "\\( N\\Phi_B = L I \\)   (Equation 6.13)",
    "where constant of proportionality L is called self-inductance of the coil.",
    "The induced back emf is:",
    "\\( \\epsilon = -L \\frac{dI}{dt} \\)   (Equation 6.14)",
    "Thus, the self-induced emf always opposes any change (increase or decrease) of",
    "current in the coil.",
    "",
    "For a long solenoid of cross-sectional area A and length l, having n turns",
    "per unit length, the self-inductance L can be derived as:",
    "\\( L = \\mu_0 n^2 A l \\)   (Equation 6.15)"
  ],
  // Page 15
  [
    "SELF INDUCTANCE (Continued)",
    "",
    "If we fill the inside of the solenoid with a material of relative permeability",
    "\\( \\mu_r \\) (for example soft iron), then:",
    "\\( L = \\mu_r \\mu_0 n^2 A l \\)   (Equation 6.16)",
    "",
    "The self-inductance of the coil depends on its geometry and on the permeability",
    "of the medium.",
    "The self-induced emf is also called the back emf as it opposes any change in",
    "the current in a circuit. Physically, the self-inductance plays the role of",
    "inertia. It is the electromagnetic analogue of mass in mechanics. So, work",
    "needs to be done against the back emf in establishing the current. This work done",
    "is stored as magnetic potential energy.",
    "",
    "For the current I at an instant in a circuit, the rate of work done is:",
    "\\( \\frac{dW}{dt} = |\\epsilon| I = L I \\frac{dI}{dt} \\)",
    "Total work done in establishing the current I is:",
    "\\( W = \\int dW = \\int_{0}^{I} L I \\, dI = \\frac{1}{2} L I^2 \\)   (Equation 6.17)",
    "Thus, the energy required to build up the current I is:",
    "\\( W = \\frac{1}{2} L I ^ 2 \\)",
    "",
    "This expression reminds us of \\( \\frac{1}{2} m v^2 \\) for the kinetic energy of a",
    "particle of mass m.",
    "",
    "Example 6.9: (a) Obtain the expression for the magnetic energy stored in",
    "a solenoid of cross-sectional area A and length l with total N turns in terms",
    "of magnetic field B. (b) Compare this magnetic energy per unit volume with",
    "the electrostatic energy stored in a capacitor.",
    "",
    "Solution:",
    "(a) Magnetic energy \\( U_B = \\frac{1}{2} L I^2 \\).",
    "Substitute \\( L = \\mu_0 n^2 A l \\) and \\( B = \\mu_0 n I \\Rightarrow I = B / (\\mu_0 n) \\).",
    "\\( U_B = \\frac{1}{2} (\\mu_0 n^2 A l) \\left(\\frac{B}{\\mu_0 n}\\right)^2 = \\frac{B^2}{2\\mu_0} A l \\).",
    "(b) Volume containing flux is V = Al. Energy density \\( u_B = U_B / V = \\frac{B^2}{2\\mu_0} \\).",
    "This matches the capacitor electrostatic energy density \\( u_E = \\frac{1}{2} \\epsilon_0 E^2 \\)."
  ],
  // Page 16
  [
    "6.8 AC GENERATOR",
    "",
    "The phenomenon of electromagnetic induction has been technologically exploited",
    "in many ways. An exceptionally important application is the generation of",
    "alternating currents (ac). The modern ac generator with a typical output",
    "capacity of 100 MW is a highly evolved machine. The Yugoslav inventor Nicola",
    "Tesla is credited with the development of the machine.",
    "",
    "One method to induce an emf or current in a loop is through a change in the loop's",
    "orientation or a change in its effective area. As the coil rotates in a magnetic",
    "field B, the effective area of the loop (the face perpendicular to the field) is",
    "\\( A \\cos \\theta \\), where \\( \\theta \\) is the angle between area vector A and",
    "magnetic field B. This is the principle of operation of a simple ac generator.",
    "An ac generator converts mechanical energy into electrical energy.",
    "",
    "The basic elements of an ac generator consist of a coil mounted on a rotor shaft.",
    "The axis of rotation of the coil is perpendicular to the direction of the",
    "magnetic field. The coil (called armature) is mechanically rotated in the uniform",
    "magnetic field by some external means. The rotation of the coil causes the",
    "magnetic flux through it to change, so an emf is induced in the coil. The ends",
    "of the coil are connected to an external circuit by means of slip rings and brushes.",
    "",
    "When the coil is rotated with a constant angular speed \\( \\omega \\), the angle",
    "\\( \\theta \\) at any instant t is \\( \\theta = \\omega t \\) (assuming \\( \\theta = 0 \\)",
    "at t = 0). As a result, the flux at any time t is:",
    "\\( \\Phi_B = BA \\cos(\\omega t) \\)",
    "From Faraday's law, the induced emf for the rotating coil of N turns is:",
    "\\( \\epsilon = -N \\frac{d\\Phi_B}{dt} = -N \\frac{d}{dt} (BA \\cos(\\omega t)) = N B A \\omega \\sin(\\omega t) \\)",
    "Thus, the instantaneous value of the emf is:",
    "\\( \\epsilon = \\epsilon_0 \\sin(\\omega t) \\)   (Equation 6.20)",
    "where \\( \\epsilon_0 = N B A \\omega \\) is the maximum value of the emf."
  ],
  // Page 17
  [
    "AC GENERATOR (Continued)",
    "",
    "Since the value of the sine function varies between +1 and -1, the sign, or",
    "polarity of the emf changes with time. The direction of the current changes",
    "periodically and therefore the current is called alternating current (ac).",
    "Since \\( \\omega = 2\\pi \\nu \\), where \\( \\nu \\) is frequency, the emf is:",
    "\\( \\epsilon = \\epsilon_0 \\sin(2\\pi \\nu t) \\)   (Equation 6.21)",
    "",
    "In commercial generators, the mechanical energy required for rotation of the",
    "armature is provided by water falling from a height (hydro-electric generators),",
    "or by steam heated by coal or other sources (thermal generators), or by nuclear",
    "fuel. Modern day generators produce electric power as high as 500 MW.",
    "",
    "Example 6.10: Kamla peddles a stationary bicycle. The pedals of the bicycle are",
    "attached to a 100 turn coil of area 0.10 m^2. The coil rotates at half a",
    "revolution per second and it is placed in a uniform magnetic field of 0.01 T",
    "perpendicular to the axis of rotation of the coil. What is the maximum voltage",
    "generated in the coil?",
    "",
    "Solution:",
    "Here, \\( \\nu = 0.5 \\text{ Hz} \\), \\( N = 100 \\), \\( A = 0.10 \\text{ m}^2 \\), \\( B = 0.01 \\text{ T} \\).",
    "The maximum voltage is:",
    "\\( \\epsilon_0 = N B A \\omega = N B A (2\\pi \\nu) \\)",
    "\\( \\epsilon_0 = 100 \\times 0.01 \\times 0.10 \\times (2 \\times 3.1416 \\times 0.5) \\)",
    "\\( \\epsilon_0 = 0.314 \\text{ V} \\).",
    "",
    "SUMMARY KEY CONCEPTS:",
    "1. Magnetic Flux linked with area A in field B is \\( \\Phi_B = B \\cdot A = BA \\cos\\theta \\).",
    "2. Faraday's Law states induced emf magnitude \\( |\\epsilon| = \\frac{d\\Phi_B}{dt} \\).",
    "3. Lenz's Law establishes direction of induced EMF: opposes flux change.",
    "4. Motional EMF across a moving conductor is \\( \\epsilon = B v l \\).",
    "5. Self-inductance of coil is L where \\( N\\Phi = L I \\); self-induced emf \\( \\epsilon = -L dI/dt \\).",
    "6. Solenoid self-inductance: \\( L = \\mu_0 n^2 A l = \\mu_0 N^2 A / l \\).",
    "7. Mutual-inductance of 2 systems: \\( M_{12} = M_{21} = M \\); emf \\( \\epsilon_1 = -M dI_2 / dt \\).",
    "8. AC Generator produces alternating emf \\( \\epsilon = N B A \\omega \\sin(\\omega t) \\)."
  ]
];

function buildPdf() {
  const targetDir = path.join(process.cwd(), 'public', 'pdfs', 'chapters');
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  const targetPath = path.join(targetDir, 'electromagnetic-induction.pdf');

  let pdfContent = '';
  // PDF Header
  pdfContent += '%PDF-1.4\r\n';

  const objects = [];
  
  // Catalog Object (Ref: 1)
  objects.push('1 0 obj\r\n<< /Type /Catalog /Pages 2 0 R >>\r\nendobj\r\n');

  // We have N pages.
  const pageRefs = [];
  const numPages = pagesData.length;
  for (let i = 0; i < numPages; i++) {
    const pageObjRef = 3 + 2 * i;
    pageRefs.push(`${pageObjRef} 0 R`);
  }

  // Pages Object (Ref: 2)
  objects.push(`2 0 obj\r\n<< /Type /Pages /Kids [${pageRefs.join(' ')}] /Count ${numPages} >>\r\nendobj\r\n`);

  // Write catalog and pages to main code
  let objIndex = 3;
  for (let i = 0; i < numPages; i++) {
    const lines = pagesData[i];
    const pageObjRef = objIndex;
    const contentObjRef = objIndex + 1;

    // Generate stream content for the page
    let streamText = '';
    streamText += 'BT\r\n';
    streamText += '/F1 10 Tf\r\n';
    streamText += '14 TL\r\n';
    streamText += '50 780 Td\r\n';

    for (let line of lines) {
      if (line === '') {
        streamText += 'T*\r\n';
      } else {
        const escaped = escapePdfString(line);
        streamText += `(${escaped}) Tj T*\r\n`;
      }
    }
    streamText += 'ET\r\n';

    const pageObj = `${pageObjRef} 0 obj\r\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /MediaBox [0 0 595 842] /Contents ${contentObjRef} 0 R >>\r\nendobj\r\n`;
    const contentObj = `${contentObjRef} 0 obj\r\n<< /Length ${streamText.length} >>\r\nstream\r\n${streamText}endstream\r\nendobj\r\n`;

    objects.push(pageObj);
    objects.push(contentObj);

    objIndex += 2;
  }

  // Assemble file body
  const bodyBufferList = [];
  const startOffset = pdfContent.length;
  const offsets = [];

  // Write objects and keep offsets
  let currentOffset = startOffset;
  
  // We write catalog
  offsets.push(currentOffset);
  const catalogStr = objects[0];
  currentOffset += Buffer.byteLength(catalogStr);
  pdfContent += catalogStr;

  // We write pages
  offsets.push(currentOffset);
  const pagesStr = objects[1];
  currentOffset += Buffer.byteLength(pagesStr);
  pdfContent += pagesStr;

  for (let i = 0; i < numPages * 2; i++) {
    offsets.push(currentOffset);
    const objStr = objects[2 + i];
    currentOffset += Buffer.byteLength(objStr);
    pdfContent += objStr;
  }

  const xrefOffset = currentOffset;
  pdfContent += 'xref\r\n';
  pdfContent += `0 ${offsets.length + 1}\r\n`;
  pdfContent += '0000000000 65535 f\r\n';
  for (let offset of offsets) {
    const paddedOffset = String(offset).padStart(10, '0');
    pdfContent += `${paddedOffset} 00000 n\r\n`;
  }

  pdfContent += 'trailer\r\n';
  pdfContent += `<< /Size ${offsets.length + 1} /Root 1 0 R >>\r\n`;
  pdfContent += 'startxref\r\n';
  pdfContent += `${xrefOffset}\r\n`;
  pdfContent += '%%EOF\r\n';

  fs.writeFileSync(targetPath, pdfContent, 'binary');
  console.log(`PDF compiled elegantly at ${targetPath}`);
}

buildPdf();
