import React, { useState } from 'react';
import { AlertCircle, BookOpen, Star, HelpCircle, Check, Compass, Info, ArrowUpRight, ShieldAlert, Award, Layers, Zap } from 'lucide-react';
import PracticeEMIInteractiveGuide from './PracticeEMIInteractiveGuide';

interface SolveState {
  [key: string]: boolean;
}

export function renderChapter6Page(pageNum: number) {
  return <Chapter6Page pageNum={pageNum} />;
}

export function Chapter6Page({ pageNum }: { pageNum: number }) {
  const [solvedState, setSolvedState] = useState<SolveState>({});

  const toggleSolve = (id: string) => {
    setSolvedState(prev => ({ ...prev, [id]: !prev[id] }));
  };

  switch (pageNum) {
    case 1:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="bg-gradient-to-r from-amber-600 to-orange-500 text-white p-8 rounded-3xl relative overflow-hidden shadow-lg border border-orange-550">
            <div className="absolute top-0 right-0 w-80 h-80 bg-white/5 rounded-full blur-3xl -mr-20 -mt-20"></div>
            <span className="text-[10px] uppercase tracking-widest font-black text-amber-100 block mb-1">
              NCERT Physics Key Textbook Page • Page 1
            </span>
            <div className="flex justify-between items-start">
              <div>
                <h1 className="text-3xl font-black tracking-tight leading-none text-slate-950 font-serif">
                  Chapter Six
                </h1>
                <h2 className="text-4xl font-extrabold tracking-tight text-white mt-1 uppercase">
                  Electromagnetic Induction
                </h2>
              </div>
              <div className="bg-slate-950 text-amber-400 font-mono text-[10px] p-2.5 rounded-lg border border-amber-400/30 text-center uppercase shrink-0 font-bold">
                CODE<br/>12089CH06
              </div>
            </div>
          </div>

          <div className="space-y-4 pt-2">
            <h3 className="text-lg font-bold text-slate-900 border-b border-slate-200 pb-1.5 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.1 INTRODUCTION
            </h3>
            <p className="text-sm font-medium leading-relaxed text-slate-705">
              Electricity and magnetism were considered separate and unrelated phenomena for a long time. In the early decades of the nineteenth century, experiments on electric current by Oersted, Ampere and a few others established the fact that electricity and magnetism are inter-related. They found that moving electric charges produce magnetic fields. For example, an electric current deflects a magnetic compass needle placed in its vicinity.
            </p>
            
            <div className="bg-orange-50 border-l-4 border-[#FF6B00] p-4 rounded-r-xl">
              <span className="text-xs font-black text-[#FF6B00] block uppercase tracking-wider">Fundamental Converse Query:</span>
              <p className="text-xs font-bold text-slate-700 mt-1 leading-relaxed">
                This naturally raises questions like: Is the converse effect possible? Can moving magnets produce electric currents? Does nature permit such a relation between electricity and magnetism?
              </p>
            </div>

            <p className="text-sm font-medium leading-relaxed text-slate-705">
              The answer is a resounding yes! The experiments of Michael Faraday in England and Joseph Henry in the USA, conducted around 1830, demonstrated conclusively that electric currents were induced in closed coils when subjected to changing magnetic fields.
            </p>
            <p className="text-sm font-semibold text-slate-900 bg-amber-50 p-3.5 rounded-xl border border-amber-100">
              The phenomenon in which electric current is generated by varying magnetic fields is appropriately called <strong>Electromagnetic Induction (EMI)</strong>.
            </p>
          </div>
        </div>
      );

    case 2:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.2 THE EXPERIMENTS OF FARADAY AND HENRY
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 2</span>
          </div>

          <p className="text-sm font-medium text-slate-700">
            The discovery and understanding of electromagnetic induction are based on a long series of experiments carried out by Faraday and Henry. We shall now describe some of these:
          </p>

          <div className="space-y-4">
            <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl relative space-y-2">
              <span className="text-[10px] font-black uppercase text-amber-600 bg-amber-50 px-2 py-0.5 rounded tracking-wide inline-block">
                Experiment 6.1
              </span>
              <h4 className="font-extrabold text-sm text-slate-900">Magnet-Coil Relative Motion</h4>
              <p className="text-xs text-slate-650 font-semibold leading-relaxed">
                A coil C1 is connected to a galvanometer G. When the North-pole of a bar magnet is pushed towards the coil, the pointer in G deflects, indicating current in the coil. The deflection lasts as long as the magnet is in motion. When pulled away, G deflects in the opposite direction. Moving the South-pole gives opposite deflections.
              </p>
              <p className="text-xs text-orange-650 bg-orange-50/70 p-2.5 rounded-lg border border-orange-100 font-bold">
                Conclusion: It is the relative motion between the magnet and the coil that is responsible for the generation (induction) of electric current in the coil.
              </p>
            </div>

            <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl relative space-y-2">
              <span className="text-[10px] font-black uppercase text-purple-600 bg-purple-50 px-2 py-0.5 rounded tracking-wide inline-block">
                Experiment 6.2
              </span>
              <h4 className="font-extrabold text-sm text-slate-900">Coil-Coil Relative Motion</h4>
              <p className="text-xs text-slate-650 font-semibold leading-relaxed">
                The bar magnet is replaced by a second coil C2 connected to a battery. The steady current in C2 produces a steady magnetic field. As C2 is moved towards the coil C1, the galvanometer G shows deflection, indicating induced current in C1.
              </p>
            </div>
          </div>
        </div>
      );

    case 3:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.3 MAGNETIC FLUX (&Phi;_B) & EXPERIMENT 6.3
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 3</span>
          </div>

          <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl space-y-2">
            <span className="text-[10px] font-black text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded uppercase">Experiment 6.3</span>
            <p className="text-xs text-slate-650 font-semibold leading-relaxed">
              Two coils C1 and C2 are held completely stationary. Coil C1 is connected to galvanometer G, while C2 is connected to a battery through a tapping key K. G shows a momentary deflection when key K is pressed, and returns to zero immediately. Steady current produces NO deflection. When K is released, another momentary deflection is seen in the opposite direction.
            </p>
          </div>

          <div className="space-y-4">
            <p className="text-sm font-medium leading-relaxed text-slate-700">
              To express these discoveries mathematically, we define <strong>magnetic flux</strong> through a plane of area A placed in a uniform magnetic field B:
            </p>

            <div className="p-5 bg-slate-900 text-slate-100 rounded-2xl border border-slate-800 font-mono text-center">
              <span className="text-[9px] uppercase tracking-wider text-slate-400 block mb-1">
                Magnetic Flux Equation
              </span>
              <div className="text-2xl font-black text-amber-400">&Phi;_B = B • A = B A cos(&theta;)</div>
              <p className="text-[11px] text-slate-400 font-sans mt-2">
                where &theta; is the angle between the directions of B and normal Area Vector A.
              </p>
            </div>

            <p className="text-xs font-semibold text-slate-600 leading-relaxed">
              The SI unit of magnetic flux is <strong>Weber (Wb)</strong> or <strong>Tesla meter squared (T m²)</strong>. It is a scalar quantity.
            </p>
          </div>
        </div>
      );

    case 4:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.4 FARADAY'S LAW OF INDUCTION
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 4</span>
          </div>

          <p className="text-sm font-medium text-slate-700 leading-relaxed">
            From the experimental observations, Faraday arrived at a conclusion that <strong>an emf is induced in a coil when the magnetic flux through the coil changes with time</strong>.
          </p>

          <div className="space-y-3 bg-slate-50 p-4 border border-slate-200 rounded-xl">
            <h4 className="text-xs font-black text-slate-900 uppercase">Explaining the Experiments:</h4>
            <ul className="list-disc pl-4 space-y-2 text-xs font-semibold text-slate-600">
              <li>In Experiment 6.1 & 6.2, relative motion changes the magnetic flux associated with the coil, inducing emf.</li>
              <li>In Experiment 6.3, tapping the key K causes the current (and resulting field flux) to rise from zero to max in a short time. This change in flux through C1 induces emf.</li>
              <li>Steady current keeps flux constant, resulting in zero induced emf.</li>
            </ul>
          </div>

          <p className="text-xs font-semibold text-slate-700">
            The common point in all observations is that the rate of change of magnetic flux through a circuit induces electromotive force (EMF) in it.
          </p>
        </div>
      );

    case 5:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              FARADAY'S LAW FORMULATION
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 5</span>
          </div>

          <div className="bg-slate-900 text-slate-100 p-6 rounded-2xl border border-slate-800 space-y-3">
            <span className="text-[9px] font-black uppercase text-green-400 bg-green-950/40 px-2 py-0.5 rounded tracking-wider">
              Mathematical Law
            </span>
            <p className="text-xs sm:text-sm font-bold leading-relaxed text-slate-200">
              "The magnitude of the induced emf in a circuit is equal to the time rate of change of magnetic flux through the circuit."
            </p>
            <div className="pt-3 border-t border-slate-800 font-mono text-center">
              <p className="text-amber-400 text-xl font-bold">e = - d&Phi;_B / dt</p>
              <p className="text-[10px] text-slate-400 mt-1">For N closely-wound turns: e = - N (d&Phi;_B / dt)</p>
            </div>
          </div>

          <div className="border border-slate-200 rounded-xl p-4 space-y-2">
            <span className="inline-block text-[9px] font-extrabold bg-blue-50 text-blue-800 px-2 py-0.5 rounded uppercase">
              Example 6.1 Study
            </span>
            <p className="text-xs text-slate-800 font-extrabold leading-snug">
              Q: (a) How to obtain a large deflection in Experiment 6.2? (b) How to demonstrate induced current without G?
            </p>
            <p className="text-xs text-slate-600 font-semibold leading-relaxed border-t border-slate-100 pt-1.5">
              <strong>Sol:</strong> (a) Step steps: Insertion of soft iron rod core inside coil, connect to high-feed active batteries, and accelerate the movement speed. (b) Replace G with a mini electric bulb; relative motion makes it glow!
            </p>
          </div>
        </div>
      );

    case 6:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              NUMERICAL STUDY: EXAMPLES 6.2 & 6.3
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 6</span>
          </div>

          <div className="space-y-4">
            <div className="bg-slate-50 border border-slate-200 p-4.5 rounded-xl space-y-2.5">
              <span className="text-[9px] font-black uppercase text-amber-700 bg-amber-100/50 px-2 py-0.5 rounded">
                Example 6.2 Formula Breakdown
              </span>
              <p className="text-xs font-bold leading-snug text-slate-900">
                A square loop of side 10 cm, resistance 0.5 &Omega;, is vertical in East-West plane inside uniform B of 0.10 T in North-East direction (&theta; = 45&deg;). Field drops steady to zero in 0.7s.
              </p>
              <button onClick={() => toggleSolve('ex62')} className="text-xs text-orange-500 hover:underline font-bold cursor-pointer">
                {solvedState['ex62'] ? 'Hide Steps' : 'See Detailed Solution'}
              </button>
              {solvedState['ex62'] && (
                <div className="text-xs text-slate-600 font-mono bg-white p-3 rounded-lg border border-slate-150 leading-relaxed animate-slide-up">
                  &Phi;_initial = B A cos(&theta;) = 0.10 * (0.1 * 0.1) * cos(45&deg;) = 10⁻³ / &radic;2 Wb.<br/>
                  &Phi;_final = 0.<br/>
                  e = |&Delta;&Phi;| / &Delta;t = (10⁻³ / &radic;2) / 0.70 = 1.0 mV.<br/>
                  I = e / R = 1.0 mV / 0.5 &Omega; = 2 mA.
                </div>
              )}
            </div>

            <div className="bg-slate-50 border border-slate-200 p-4.5 rounded-xl space-y-2.5">
              <span className="text-[9px] font-black uppercase text-amber-700 bg-amber-100/50 px-2 py-0.5 rounded">
                Example 6.3 Formula Breakdown
              </span>
              <p className="text-xs font-bold leading-snug text-slate-900">
                A circular coil of radius 10 cm, 500 turns, and 2 &Omega; resistance, vertical diameter rotation of 180&deg; inside earth field B_H = 3.0 &times; 10⁻⁵ T in 0.25 s.
              </p>
              <button onClick={() => toggleSolve('ex63')} className="text-xs text-orange-500 hover:underline font-bold cursor-pointer">
                {solvedState['ex63'] ? 'Hide Steps' : 'See Detailed Solution'}
              </button>
              {solvedState['ex63'] && (
                <div className="text-xs text-slate-600 font-mono bg-white p-3 rounded-lg border border-slate-150 leading-relaxed animate-slide-up">
                  &Phi;_initial = B A cos(0&deg;) = 3.0 &times; 10⁻⁵ * (&pi; &times; 10⁻²) = 3&pi; &times; 10⁻⁷ Wb.<br/>
                  &Phi;_final = B A cos(180&deg;) = -3&pi; &times; 10⁻⁷ Wb.<br/>
                  e = N |&Delta;&Phi;| / &Delta;t = 500 * (6&pi; &times; 10⁻⁷) / 0.25 = 3.8 mV.<br/>
                  I = e / R = 3.8 mV / 2 &Omega; = 1.9 mA.
                </div>
              )}
            </div>
          </div>
        </div>
      );

    case 7:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.5 LENZ'S LAW & CONSERVATION OF ENERGY
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 7</span>
          </div>

          <div className="bg-orange-50 border-l-4 border-orange-500 p-5 rounded-r-2xl">
            <span className="text-xs font-black text-orange-850 uppercase tracking-widest block mb-0.5">Lenz's Law (German Physicist Heinrich Lenz, 1834):</span>
            <blockquote className="text-sm font-extrabold italic text-slate-900 leading-relaxed">
              "The polarity of the induced emf is such that it tends to produce a current which opposes the change in magnetic flux that produced it."
            </blockquote>
          </div>

          <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl space-y-3">
            <h4 className="font-extrabold text-xs tracking-wider uppercase text-slate-900">Thermodynamic Rigorous Connection:</h4>
            <p className="text-xs text-slate-650 font-semibold leading-relaxed">
              Suppose the induced current did NOT oppose the approach of the magnet's N-pole, but created a South pole instead. The magnet would instantly accelerate towards the loop carrying zero push. Kinetic energy and Joule heating would rise indefinitely without input, defying the <strong>Law of Conservation of Energy</strong>.
            </p>
            <p className="text-xs text-slate-600 font-bold bg-white p-2 border border-slate-150 rounded">
              Therefore, the induced current MUST create a repelling North-pole face. The mechanical work done to push against this magnetic repulsion converts directly into electrical energy.
            </p>
          </div>
        </div>
      );

    case 8:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              LENZ'S LAW PRACTICE PROBLEMS: EXAMPLES 6.4 & 6.5
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 8</span>
          </div>

          <div className="space-y-4">
            <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-1.5">
              <span className="text-[10px] uppercase font-black text-amber-700">Example 6.4 Direction Solver</span>
              <p className="text-xs text-slate-800 font-extrabold">Determine induced current directions in loops moving inside a magnetic field pointing perpendicularly away from the reader (into the paper):</p>
              <ul className="list-decimal pl-4 text-xs text-slate-600 font-semibold space-y-1.5">
                <li><strong>Rectangular loop:</strong> Entering the field &rarr; flux increases &rarr; induced field must point out (towards reader) &rarr; Current direction: <strong>Counter-clockwise (bcdab)</strong>.</li>
                <li><strong>Triangular loop:</strong> Leaving the field &rarr; flux decreases &rarr; need reinforcing field &rarr; Current direction: <strong>Clockwise (bacb)</strong>.</li>
              </ul>
            </div>

            <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-1.5">
              <span className="text-[10px] uppercase font-black text-amber-700">Example 6.5 Conceptual</span>
              <p className="text-xs text-slate-850 font-extrabold">Q: A loop is stationary inside very strong constant magnet pole-caps. Can we expect current generation?</p>
              <p className="text-xs text-slate-600 font-semibold">Answer: No. However strong the magnet is, magnetic induction strictly requires a <strong>changing</strong> flux over time.</p>
            </div>
          </div>
        </div>
      );

    case 9:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.6 MOTIONAL ELECTROMOTIVE FORCE (EMF)
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 9</span>
          </div>

          <p className="text-sm font-medium text-slate-705">
            Let us consider a straight conductor PQ of length <em>l</em> sliding along a U-shaped conductor rails in a uniform magnetic field B perpendicular to the plane of rails. If the sliding distance is x, the enclosed loop flux is &Phi;_B = B l x.
          </p>

          <div className="bg-slate-900 text-slate-100 p-5 rounded-2xl border border-slate-800 text-center font-mono">
            <span className="text-[9px] uppercase tracking-wider text-slate-400 block mb-1">Motional EMF Derivation</span>
            <div className="text-xl font-bold text-emerald-400">e = - d&Phi;_B/dt = - d(Blx)/dt = - B l (dx/dt)</div>
            <p className="text-xs text-amber-400 mt-2 font-bold mb-1">Since code rod moves with velocity towards left, vector dx/dt = -v:</p>
            <div className="text-2xl font-black text-amber-400">e = B l v</div>
          </div>

          <div className="p-4 bg-orange-50 border border-orange-100 rounded-xl">
            <h5 className="text-xs font-bold text-orange-800 uppercase flex items-center gap-1.5">
              <Award className="w-4 h-4 shrink-0 text-orange-500" /> Lorentz Charge Vector Proof:
            </h5>
            <p className="text-xs text-slate-700 font-semibold mt-1">
              Lorentz magnetic force on unit free charge q inside PQ is <strong>F_mag = q v B</strong>. Work done in moving charge q from P to Q is <strong>W = F * l = q v B l</strong>. Since EMF represents work done per unit charge, we get: <strong>e = W/q = B l v</strong>.
            </p>
          </div>
        </div>
      );

    case 10:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              MOTIONAL EMF IN STATIONARY CIRCUITS & ROTATION
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 10</span>
          </div>

          <p className="text-sm font-medium text-slate-750">
            When a conductor is stationary and the magnetic field changes, relative velocity v=0. The Lorentz force equation becomes <strong>F = q E</strong>. This means that a time-varying magnetic field physically creates an electric field in space!
          </p>

          <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl space-y-3">
            <span className="text-[10px] bg-sky-100 text-sky-850 px-2 py-0.5 rounded tracking-wider font-extrabold uppercase inline-block">
              Example 6.6 Rotating Rod
            </span>
            <p className="text-xs text-slate-900 font-extrabold leading-snug">
              A metallic rod of length 1 m is rotated with frequency 50 rev/s about one hinged end in a uniform magnetic field 1 T parallel to the axis. Find the induced EMF.
            </p>
            <button onClick={() => toggleSolve('ex66')} className="text-xs text-orange-500 hover:underline font-bold cursor-pointer">
              {solvedState['ex66'] ? 'Hide Formula steps' : 'See Method I Integration Solution'}
            </button>
            {solvedState['ex66'] && (
              <div className="text-xs font-mono text-slate-600 bg-white p-3 rounded-lg border border-slate-150 leading-relaxed space-y-2 animate-slide-up">
                <p>Induced EMF on small segment dr at distance r is d&epsilon; = B * v * dr = B * &omega; * r * dr.</p>
                <p>&epsilon; = &int; (B &omega; r dt) from 0 to R = B &omega; R² / 2.</p>
                <p>&omega; = 2&pi;f = 2&pi; * 50 = 100&pi; rad/s. R = 1 m, B = 1 T.</p>
                <p>&epsilon; = (1 &times; 100&pi; &times; 1²) / 2 = 50&pi; &approx; 157 V.</p>
              </div>
            )}
          </div>
        </div>
      );

    case 11:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              ROTATION METHOD II & THE WHEEL CORE SPOKES
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 11</span>
          </div>

          <p className="text-sm font-medium text-slate-705">
            Another gorgeous logical path for Example 6.6 rotates rod segment OPQ: Area of the sector is <strong>A = 1/2 R² &theta;</strong>. EMF is:
          </p>
          <div className="bg-slate-950 text-sky-300 p-4.5 rounded-xl border border-sky-400/20 text-center font-mono text-xs">
            e = B (dA/dt) = B d(1/2 R² &theta;)/dt = 1/2 B R² (d&theta;/dt) = 1/2 B R² &omega;
          </div>

          <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-2">
            <span className="text-[10px] font-black uppercase text-amber-700 bg-amber-100 px-2 py-0.5 rounded tracking-wider">Example 6.7: Metal Spokes Wheel</span>
            <p className="text-xs text-slate-900 font-bold leading-snug">
              A wheel with 10 metallic spokes each 0.5 m long is rotated at 120 rev/min inside horizontal earth magnetic field B_H = 0.4 G = 0.4 &times; 10⁻⁴ T. What is the induced EMF between the axle and rim?
            </p>
            <p className="text-xs text-slate-600 font-semibold leading-relaxed border-t border-slate-100 pt-1.5">
              <strong>Sol:</strong> Induced emf = 1/2 B &omega; R². <br/>
              &omega; = 120 rev/min = 2 rev/s = 4&pi; rad/s. R = 0.5 m. <br/>
              e = 1/2 &times; (0.4 &times; 10⁻⁴ T) &times; (4&pi;) &times; (0.25) &approx; <strong>6.28 &times; 10⁻⁵ V</strong>. <br/>
              <span className="text-amber-800 font-bold">Important note:</span> The number of spokes is completely immaterial because they are connected in parallel!
            </p>
          </div>
        </div>
      );

    case 12:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.7 INDUCTANCE & MUTUAL INDUCTION
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 12</span>
          </div>

          <p className="text-sm font-medium text-slate-700 leading-relaxed">
            Whenever the current in a coil changes, the magnetic flux linked with itself or a neighbouring coil changes, inducing electromotive force. Flux linkage is directly proportional to current: <strong>N &Phi;_B &propto; I</strong>. The proportionality constant is called <strong>Inductance</strong> (SI unit: Henry [H]).
          </p>

          <h4 className="text-md font-bold text-slate-900 border-b border-slate-100 pb-1">6.7.1 Mutual Inductance</h4>
          <p className="text-xs text-slate-650 font-semibold leading-relaxed">
            Consider two long co-axial solenoids each of length <em>l</em>. Inner solenoid S1 (radius r1, turns n1 per unit length). Outer solenoid S2 (radius r2, turns n2).
          </p>

          <div className="bg-slate-900 text-slate-100 p-4.5 rounded-2xl border border-slate-800 space-y-1.5 text-xs font-mono">
            <span className="text-slate-400 block font-sans text-[10px] uppercase font-bold">Flux Linkage with S1 due to current I2 in S2:</span>
            <p>N1 &Phi;1 = M12 I2</p>
            <p>B2 = &mu;0 n2 I2</p>
            <p className="text-emerald-400">M12 = &mu;0 n1 n2 &pi; r1&sup2; l</p>
          </div>
        </div>
      );

    case 13:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              MUTUAL INDUCTANCE EQUALITY AND COILS
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 13</span>
          </div>

          <div className="space-y-3.5">
            <p className="text-sm font-medium text-slate-700 leading-relaxed">
              If a current I1 is passed through the inner solenoid S1, the flux linkage with the outer solenoid S2 is:
            </p>
            <div className="bg-slate-950 text-sky-300 p-4 rounded-xl border border-sky-400/20 text-center font-mono text-xs">
              M21 = &mu;0 n1 n2 &pi; r1&sup2; l
            </div>
            <p className="text-xs text-slate-650 font-semibold leading-relaxed">
              This proves that the mutual inductance of coil 1 with respect to coil 2 is exactly equal to that of coil 2 with respect to coil 1: <strong>M12 = M21 = M</strong>.
            </p>

            <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl space-y-2">
              <span className="text-[10px] uppercase tracking-wide bg-amber-150 bg-amber-200 text-slate-950 font-black px-2 py-0.5 rounded">
                Example 6.8: Two concentric circles
              </span>
              <p className="text-xs text-slate-900 font-extrabold">Two concentric circular coils, radii r1 and r2 (r1 &ll; r2), coinciding centers. Obtain mutual inductance.</p>
              <p className="text-xs text-slate-600 font-semibold leading-relaxed">
                <strong>Solution:</strong> Let current I2 flow in the outer coil. Magnetic field at the center is B2 = &mu;0 I2 / 2r2. Since r1 is small, field is uniform. Flux in inner: &Phi;1 = &pi; r1&sup2; B2 = &mu;0 &pi; r1&sup2; I2 / 2r2. <br/>
                Hence: <strong>M = &mu;0 &pi; r1&sup2; / 2r2</strong>.
              </p>
            </div>
          </div>
        </div>
      );

    case 14:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              MUTUAL EMF FORMULA & 6.7.2 SELF INDUCTION
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 14</span>
          </div>

          <div className="space-y-4">
            <p className="text-sm font-medium text-slate-705">
              If an iron core of relative permeability &mu;_r is put inside, mutual inductance increases: <strong>M = &mu;_r &mu;_0 n1 n2 &pi; r1&sup2; l</strong>. The induced EMF is:
            </p>
            <div className="bg-slate-900 text-white p-4 rounded-xl border border-slate-800 text-center font-mono text-sm font-bold">
              e1 = - M (dI2 / dt)
            </div>

            <h4 className="text-md font-bold text-slate-900 flex items-center gap-1.5 border-b border-slate-100 pb-1">
              <span className="w-2 h-3 bg-orange-500 rounded"></span>
              6.7.2 Self Inductance
            </h4>
            <p className="text-xs text-slate-650 font-semibold leading-relaxed">
              When current inside a single isolated coil changes with time, flux linked with it changes, inducing a backing electromotive force in the same coil. This is self-induction.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
                <span className="font-sans font-bold text-slate-600 block mb-1">Self-Inductor Linkage</span>
                N &Phi;_B = L I
              </div>
              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
                <span className="font-sans font-bold text-slate-600 block mb-1">Self-Induced Back EMF</span>
                e = - L (dI / dt)
              </div>
            </div>
            <p className="text-xs text-slate-605 font-bold">
              For a long solenoid of area A, length l, with n turns per unit length, self-inductance: <strong>L = &mu;0 n&sup2; A l = &mu;0 N&sup2; A / l</strong>.
            </p>
          </div>
        </div>
      );

    case 15:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              ELECTROMAGNETIC INERTIA & ENERGY DENSITY
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 15</span>
          </div>

          <p className="text-sm font-medium text-slate-705 leading-relaxed">
            The self-inductance of a coil physically plays the role of <strong>inertia</strong> (electromagnetic analogue of mass in mechanics). Work done in establishing a current I against this back emf is stored as magnetic potential energy inside the field:
          </p>

          <div className="bg-slate-950 text-emerald-400 p-5 rounded-2xl border border-white/10 text-center font-mono">
            <span className="text-slate-400 block font-sans text-xs mb-1">Stored Magnetic Potential Energy:</span>
            <div className="text-2xl font-black">W = 1/2 L I&sup2;</div>
          </div>

          <div className="bg-slate-50 border border-slate-200 p-4.5 rounded-xl space-y-2">
            <span className="text-[10px] font-black uppercase text-amber-700 bg-amber-100 px-2 py-0.5 rounded">Example 6.9 Energy density</span>
            <p className="text-xs text-slate-900 font-extrabold leading-snug">Q: (a) Obtain magnetic energy stored in solenoid inside field B. (b) Compare energy density per unit volume with a capacitor.</p>
            <p className="text-xs text-slate-650 font-semibold leading-relaxed border-t border-slate-100 pt-1.5">
              <strong>Sol:</strong> (a) L = &mu;0 n&sup2; A l; B = &mu;0 n I. Energy U_B = 1/2 L I&sup2; = B&sup2; A l / 2&mu;0. <br/>
              (b) Solar volume V = A l. Magnetic Energy Density <strong>u_B = U_B / V = B&sup2; / 2&mu;0</strong>. This matches electric capacitor storage <strong>u_E = 1/2 &epsilon;o E&sup2;</strong> perfectly!
            </p>
          </div>
        </div>
      );

    case 16:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              6.8 ALTERNATING CURRENT (AC) GENERATOR
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 16</span>
          </div>

          <p className="text-sm font-medium text-slate-705 leading-relaxed">
            An exceptionally important visual application of electromagnetic induction is the AC Generator, developed by inventor <strong>Nikola Tesla</strong>. It converts mechanical energy into electrical energy by rotating armature coils in magnetic fields.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-1">
              <span className="text-[9px] text-[#FF6B00] font-black uppercase">Principle</span>
              <p className="text-xs text-slate-650 font-semibold">The armature coil of N turns and area A is rotated with constant angular velocity &omega;. The angle is &theta; = &omega;t, and the changing flux is &Phi;_B = B A cos(&omega;t).</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-1">
              <span className="text-[9px] text-purple-600 font-black uppercase">Induced Voltage</span>
              <p className="text-xs text-slate-650 font-semibold">Applying Faraday laws: e = - N d&Phi;_B/dt = N B A &omega; sin(&omega;t).</p>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 text-slate-100 p-5 rounded-2xl text-center font-mono">
            <span className="text-[9px] text-slate-400 uppercase tracking-widest block mb-1">Instantaneous AC Voltage</span>
            <div className="text-2xl font-black text-amber-400">e = e₀ sin(&omega;t)</div>
            <span className="text-[10px] text-slate-400 block mt-1">where peak voltage e₀ = N B A &omega;</span>
          </div>
        </div>
      );

    case 17:
      return (
        <div className="space-y-6 text-slate-800 leading-relaxed font-sans animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-200 pb-1.5">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="w-2.5 h-4 bg-orange-500 rounded"></span>
              AC NUMERICAL & CHAPTER CORE RECAP
            </h3>
            <span className="text-xs text-slate-400 font-mono">Page 17</span>
          </div>

          <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl space-y-1.5">
            <span className="text-[9px] text-[#FF6B00] font-black uppercase bg-orange-100 px-2 py-0.5 rounded">Example 6.10 Bicycle dynamo</span>
            <p className="text-xs text-slate-950 font-extrabold">Kamla rotates a 100 turns coil of area 0.10 m² at f = 0.5 rev/s perpendicular in B = 0.01 T. Find max voltage.</p>
            <p className="text-xs text-slate-650 font-semibold leading-relaxed border-t border-slate-100 pt-1">
              <strong>Sol:</strong> e₀ = N B A &omega; = N B A (2&pi;f) = 100 * 0.01 * 0.10 * (2 * 3.1416 * 0.5) = <strong>0.314 V</strong>.
            </p>
          </div>

          <div className="bg-slate-900 text-slate-100 p-5 rounded-2xl border border-slate-800 space-y-3">
            <h4 className="text-xs font-black text-amber-400 uppercase tracking-widest">CHAPTER 6 CORE SUMMARY BULLETS:</h4>
            <ul className="text-xs font-semibold text-slate-350 space-y-2 list-decimal pl-4 text-slate-300 marker:text-amber-500">
              <li><strong>Magnetic Flux:</strong> Scalar product of field and surface representation vector dot product: &Phi; = B &bull; A.</li>
              <li><strong>Faraday Law:</strong> Induced EMF matches the temporal flux derivatives: e = - d&Phi;/dt.</li>
              <li><strong>Lenz Law:</strong> Back electromotive polarity resists incoming alterations (energy conservation).</li>
              <li><strong>Inductance (Henry):</strong> Electromagnetic inertia coefficient storage metric: L and M.</li>
            </ul>
          </div>

          {/* Practice component hook */}
          <div className="border-t border-slate-200 pt-4 space-y-2">
            <span className="text-xs font-black uppercase text-indigo-700 tracking-wider block">Interactive Practice Dashboard:</span>
            <PracticeEMIInteractiveGuide />
          </div>
        </div>
      );

    default:
      return <div className="p-12 text-center text-slate-500 font-bold">NCERT Class 11 Physics Chapter 6. Selected page out of limits.</div>;
  }
}
